### ISSUE TITLE
Crash when exiting SteamVR

### ISSUE THREAD

**Issue by deinlandel** [matzman666/OpenVR-AdvancedSettings#10] opened 2016-11-21 08:30 UTC
Openvr advanced settings crashes when I exit SteamVR.
```
  APPCRASH
  App name:	AdvancedSettings.exe
  Version:	0.0.0.0
  App timestamp:	581392b3
  Name of the module with error:	ucrtbase.DLL
  Version of the module with error:	10.0.10240.16390
  Timestamp of the module with error:	55a5b718
  Exception code:	40000015
  Exception offset:	0000000000065a5f
  OS version:	6.1.7601.2.1.0.256.1
  Language code:	1049
  Additional settings 1:	a4bf
  Additional settings 2:	a4bfa07a344ea50d115478ccbfb207eb
  Additional settings 3:	03e4
  Additional settings 4:	03e4e7f3e6fee07c5638034b206fb04b
```

**Comment by deinlandel** [comment] 2016-11-21 08:31
AdvancedSettings.log:
```
[INFO ] 2016-11-21 10:26:50: Starting Application.
[INFO ] 2016-11-21 10:26:50: Settings File: V:/Users/Deinlandel/AppData/Roaming/matzman666/OpenVRAdvancedSettings.ini
[INFO ] 2016-11-21 10:26:51: VR Runtime Path: Y:/Games-inst/Steam/steamapps/common/SteamVR/
[INFO ] 2016-11-21 13:24:11: Received quit request.
[FATAL] 2016-11-21 13:24:11: CRASH HANDLED; Application has crashed due to [SIGSEGV] signal
```

**Comment by deinlandel** [comment] 2016-11-21 08:32
OpenVRAdvancedSettings.ini:
```
[chaperoneSettings]
chaperoneProfiles\1\profileName=video
chaperoneProfiles\1\includesChaperoneGeometry=true
chaperoneProfiles\1\chaperoneGeometryQuadCount=8
chaperoneProfiles\1\chaperoneGeometryQuads=@Variant(\0\0\0\t\0\0\0\x4\0\0\0\t\0\0\0\x3\0\0\0\x87?\xa5\x83\x66\0\0\0\x87\0\0\0\0\0\0\0\x87\xbf\xae\x80R\0\0\0\t\0\0\0\x3\0\0\0\x87?\xa5\x83\x66\0\0\0\x87@\x1b\x85\x1f\0\0\0\x87\xbf\xae\x80R\0\0\0\t\0\0\0\x3\0\0\0\x87\xbe\xb2?G\0\0\0\x87@\x1b\x85\x1f\0\0\0\x87\xbf\x9b\x86r\0\0\0\t\0\0\0\x3\0\0\0\x87\xbe\xb2?G\0\0\0\x87\0\0\0\0\0\0\0\x87\xbf\x9b\x86r), @Variant(\0\0\0\t\0\0\0\x4\0\0\0\t\0\0\0\x3\0\0\0\x87\xbe\xb2?G\0\0\0\x87\0\0\0\0\0\0\0\x87\xbf\x9b\x86r\0\0\0\t\0\0\0\x3\0\0\0\x87\xbe\xb2?G\0\0\0\x87@\x1b\x85\x1f\0\0\0\x87\xbf\x9b\x86r\0\0\0\t\0\0\0\x3\0\0\0\x87\xbf\xca\x1e\x81\0\0\0\x87@\x1b\x85\x1f\0\0\0\x87\xbf\x90\xcc\xa4\0\0\0\t\0\0\0\x3\0\0\0\x87\xbf\xca\x1e\x81\0\0\0\x87\0\0\0\0\0\0\0\x87\xbf\x90\xcc\xa4), @Variant(\0\0\0\t\0\0\0\x4\0\0\0\t\0\0\0\x3\0\0\0\x87\xbf\xca\x1e\x81\0\0\0\x87\0\0\0\0\0\0\0\x87\xbf\x90\xcc\xa4\0\0\0\t\0\0\0\x3\0\0\0\x87\xbf\xca\x1e\x81\0\0\0\x87@\x1b\x85\x1f\0\0\0\x87\xbf\x90\xcc\xa4\0\0\0\t\0\0\0\x3\0\0\0\x87\xc0\x5\xc1[\0\0\0\x87@\x1b\x85\x1f\0\0\0\x87\xbc\x46\x12\xa3\0\0\0\t\0\0\0\x3\0\0\0\x87\xc0\x5\xc1[\0\0\0\x87\0\0\0\0\0\0\0\x87\xbc\x46\x12\xa3), @Variant(\0\0\0\t\0\0\0\x4\0\0\0\t\0\0\0\x3\0\0\0\x87\xc0\x5\xc1[\0\0\0\x87\0\0\0\0\0\0\0\x87\xbc\x46\x12\xa3\0\0\0\t\0\0\0\x3\0\0\0\x87\xc0\x5\xc1[\0\0\0\x87@\x1b\x85\x1f\0\0\0\x87\xbc\x46\x12\xa3\0\0\0\t\0\0\0\x3\0\0\0\x87\xc0\x2\x11\xcd\0\0\0\x87@\x1b\x85\x1f\0\0\0\x87?(\xb9\xbb\0\0\0\t\0\0\0\x3\0\0\0\x87\xc0\x2\x11\xcd\0\0\0\x87\0\0\0\0\0\0\0\x87?(\xb9\xbb), @Variant(\0\0\0\t\0\0\0\x4\0\0\0\t\0\0\0\x3\0\0\0\x87\xc0\x2\x11\xcd\0\0\0\x87\0\0\0\0\0\0\0\x87?(\xb9\xbb\0\0\0\t\0\0\0\x3\0\0\0\x87\xc0\x2\x11\xcd\0\0\0\x87@\x1b\x85\x1f\0\0\0\x87?(\xb9\xbb\0\0\0\t\0\0\0\x3\0\0\0\x87\xbf\xe6\xf4\x92\0\0\0\x87@\x1b\x85\x1f\0\0\0\x87?\x8d&\x8c\0\0\0\t\0\0\0\x3\0\0\0\x87\xbf\xe6\xf4\x92\0\0\0\x87\0\0\0\0\0\0\0\x87?\x8d&\x8c), @Variant(\0\0\0\t\0\0\0\x4\0\0\0\t\0\0\0\x3\0\0\0\x87\xbf\xe6\xf4\x92\0\0\0\x87\0\0\0\0\0\0\0\x87?\x8d&\x8c\0\0\0\t\0\0\0\x3\0\0\0\x87\xbf\xe6\xf4\x92\0\0\0\x87@\x1b\x85\x1f\0\0\0\x87?\x8d&\x8c\0\0\0\t\0\0\0\x3\0\0\0\x87?\xc7\xcd.\0\0\0\x87@\x1b\x85\x1f\0\0\0\x87?\x8f\x9e\x44\0\0\0\t\0\0\0\x3\0\0\0\x87?\xc7\xcd.\0\0\0\x87\0\0\0\0\0\0\0\x87?\x8f\x9e\x44), @Variant(\0\0\0\t\0\0\0\x4\0\0\0\t\0\0\0\x3\0\0\0\x87?\xc7\xcd.\0\0\0\x87\0\0\0\0\0\0\0\x87?\x8f\x9e\x44\0\0\0\t\0\0\0\x3\0\0\0\x87?\xc7\xcd.\0\0\0\x87@\x1b\x85\x1f\0\0\0\x87?\x8f\x9e\x44\0\0\0\t\0\0\0\x3\0\0\0\x87?\xbf\xdf\xf6\0\0\0\x87@\x1b\x85\x1f\0\0\0\x87\xbf\x9e\xf7\xea\0\0\0\t\0\0\0\x3\0\0\0\x87?\xbf\xdf\xf6\0\0\0\x87\0\0\0\0\0\0\0\x87\xbf\x9e\xf7\xea), @Variant(\0\0\0\t\0\0\0\x4\0\0\0\t\0\0\0\x3\0\0\0\x87?\xbf\xdf\xf6\0\0\0\x87\0\0\0\0\0\0\0\x87\xbf\x9e\xf7\xea\0\0\0\t\0\0\0\x3\0\0\0\x87?\xbf\xdf\xf6\0\0\0\x87@\x1b\x85\x1f\0\0\0\x87\xbf\x9e\xf7\xea\0\0\0\t\0\0\0\x3\0\0\0\x87?\xa5\x83\x66\0\0\0\x87@\x1b\x85\x1f\0\0\0\x87\xbf\xae\x80R\0\0\0\t\0\0\0\x3\0\0\0\x87?\xa5\x83\x66\0\0\0\x87\0\0\0\0\0\0\0\x87\xbf\xae\x80R)
chaperoneProfiles\1\standingCenter=@Variant(\0\0\0\t\0\0\0\x4\0\0\0\x87\xbe\xa6\xb0\xe5\0\0\0\x87\0\0\0\0\0\0\0\x87?r\r\x80\0\0\0\x87\xbe\xcf\xfc\x14), @Variant(\0\0\0\t\0\0\0\x4\0\0\0\x87\0\0\0\0\0\0\0\x87?\x80\0\0\0\0\0\x87\0\0\0\0\0\0\0\x87\xbf\x8b\xaf\x81), @Variant(\0\0\0\t\0\0\0\x4\0\0\0\x87\xbfr\r\x80\0\0\0\x87\0\0\0\0\0\0\0\x87\xbe\xa6\xb0\xe5\0\0\0\x87\xc0\x16\xf3.)
chaperoneProfiles\1\playSpaceAreaX=@Variant(\0\0\0\x87@?\xff\xfe)
chaperoneProfiles\1\playSpaceAreaZ=@Variant(\0\0\0\x87@\f\xcc\xce)
chaperoneProfiles\1\includesVisibility=false
chaperoneProfiles\1\includesFadeDistance=false
chaperoneProfiles\1\includesCenterMarker=false
chaperoneProfiles\1\includesPlaySpaceMarker=true
chaperoneProfiles\1\playSpaceMarker=false
chaperoneProfiles\1\includesFloorBoundsMarker=false
chaperoneProfiles\1\includesBoundsColor=true
chaperoneProfiles\1\boundsColor=0, 255, 255
chaperoneProfiles\1\includesChaperoneStyle=true
chaperoneProfiles\1\chaperoneStyle=3
chaperoneProfiles\1\includesForceBounds=false
chaperoneProfiles\size=1
```

**Comment by deinlandel** [comment] 2016-11-21 08:34
SteamVR info:
Built nov 15, 2016 at 03:50
Version 1479163853

(latest stable version at the moment with async timewarp support)

**Comment by matzman666** [comment] 2016-11-22 19:08
I cannot reproduce this problem. It seems that only Win7 is affected by this (I am using Win10, maybe that's why I cannot reproduce it). Are you using Win7?

**Comment by deinlandel** [comment] 2016-11-23 11:10
Yes, I am using Windows 7 64 bit.

**Comment by digitaldazz** [comment] 2016-11-23 18:03
Same for me on Windows 7 64 bit.

**Comment by smygarn** [comment] 2016-11-28 19:13
Also got a crash when exit SteamVR. Windows 10 64bit here. (Steam VR Beta)

**Comment by biosmanager** [comment] 2016-12-03 18:31
Also crashing for me when exiting. Windows 10 64-bit
The warning log message is also empty.

```[INFO ] 2016-11-30 00:19:24: Starting Application.
[INFO ] 2016-11-30 00:19:24: Settings File: C:/Users/biosm/AppData/Roaming/matzman666/OpenVRAdvancedSettings.ini
[INFO ] 2016-11-30 00:19:24: VR Runtime Path: C:/Program Files (x86)/Steam/steamapps/common/SteamVR/
[INFO ] 2016-11-30 00:22:06: Received quit request.
[WARN ] 2016-11-30 00:22:06: 
[INFO ] 2016-11-30 00:23:27: Starting Application.
[INFO ] 2016-11-30 00:23:27: Settings File: C:/Users/biosm/AppData/Roaming/matzman666/OpenVRAdvancedSettings.ini
[INFO ] 2016-11-30 00:23:27: VR Runtime Path: C:/Program Files (x86)/Steam/steamapps/common/SteamVR/
[INFO ] 2016-11-30 00:37:07: Received quit request.
[WARN ] 2016-11-30 00:37:07: 
[INFO ] 2016-11-30 00:38:26: Starting Application.
[INFO ] 2016-11-30 00:38:26: Settings File: C:/Users/biosm/AppData/Roaming/matzman666/OpenVRAdvancedSettings.ini
[INFO ] 2016-11-30 00:38:26: VR Runtime Path: C:/Program Files (x86)/Steam/steamapps/common/SteamVR/
[INFO ] 2016-11-30 00:39:59: Received quit request.
[INFO ] 2016-12-03 18:12:17: Starting Application.
[INFO ] 2016-12-03 18:12:18: Settings File: C:/Users/biosm/AppData/Roaming/matzman666/OpenVRAdvancedSettings.ini
[INFO ] 2016-12-03 18:12:18: VR Runtime Path: C:/Program Files (x86)/Steam/steamapps/common/SteamVR/
[INFO ] 2016-12-03 19:24:50: Received quit request.
[WARN ] 2016-12-03 19:24:50:

**Comment by matzman666** [comment] 2016-12-09 22:34
Should be fixed in the newest version. Please test it.

**Closed** 2017-01-11 23:28 UTC
