### ISSUE TITLE
Revive settings tab

### ISSUE THREAD

**Issue by LibreVR** [matzman666/OpenVR-AdvancedSettings#19] opened 2016-12-10 19:35 UTC
I've got a bunch of OpenVR settings for Revive that I need to make an option panel for. But I don't really want to add an option panel to the Revive Dashboard.

So how about we do a collaboration? Could you add a tab for Revive in the OpenVR Advanced Settings?

You can use the OpenVR Applications API to detect whether Revive is installed (the appkey is `revive.dashboard.overlay`) and only show the tab to users who have Revive installed.

If you're interested, I can compile a list of settings for Revive and we can discuss how we can go about collaborating on this.

**Comment by matzman666** [comment] 2016-12-10 20:46
Yeah, sure. I can add a Revive page. Just tell me what you want to have on the Revive page.

**Comment by LibreVR** [comment] 2016-12-10 22:33
The most important option is `ToggleGrip` which allows you to use the grip button as a toggle instead of having to keep to pressed. This will be expanded with a `HybridGrip` option that allows you to enable toggle on a short press of the grip buttons.

Next there's the `pixelsPerDisplayPixel` option. This will override the Oculus internal render target multiplier which is sometimes set to lower or higher values by the game. This should consist of a checkbox that indicates whether the override is active and a slider that allows you to set the multiplier. If not checked, the key should be removed using `vr::VRSettings()->RemoveKeyInSection()`.

And there are a couple more advanced controller options: `ThumbDeadzone` determines the distance you need to move your thumb before the thumbstick activates and `ThumbRange` determines its sensitivity.

Last, but not least: there's the Oculus Touch locations/rotation offset parameters: `TouchPitch TouchYaw TouchRoll TouchX TouchY TouchZ`. The rotations are in degrees and the positions are in meters.

**Comment by LibreVR** [comment] 2016-12-10 22:40
There are also some interesting Oculus settings that Revive translates. You can set things like `PlayerHeight` and `EyeHeight`, but I don't know whether there are any games that actually use this.

There's also some string values like `User`, `Name`, and `Gender` (which can be "Male", "Female", or "Unknown").

**Comment by matzman666** [comment] 2016-12-12 21:36
I have committed a first draft for the revive page (Commit 7fafebcd47f4f11c28b480154c9bcd39d2f74bff). No polish and no functionality, just a mockup for now to see how much space the options need.

To be able to see it, just download the current release and replace the files in the folder res/qml with the ones from the commit.

**Comment by LibreVR** [comment] 2016-12-12 22:00
Thanks, I'll take a look at it tomorrow.

**Comment by LibreVR** [comment] 2016-12-13 20:57
That looks great, you got every setting in there :+1: 

Now we need to figure out a good way to handle the default values, we have two options:

1. I give you the defaults from Revive and you hardcode them, I'll submit a PR every time I change the values.
2. I change the Revive Dashboard to add the default values to the `default.vrsettings`. That way I can update the defaults when I need to and you can just get the default value if it is not already set just like the other SteamVR settings.

I think (2) is the preferred solution here, what do you think?

**Comment by matzman666** [comment] 2016-12-14 18:10
In my opinion both approaches are not really optimal. With (1) you need to submit a PR everytime something changes, and with (2) you need to update Revive everytime Valve updates the default.vrsettings.

I would stick with (1) because the potential fallout in case of problems is smaller. With (2) SteamVR could be completely broken when someone installs an outdated Revive version which misses some newly added default values, or Revive could be completely broken whenever SteamVR updates the default.vrsettings and erases all Revive defaults. With (1) the only thing that could happen that some default values may be different, but nothing breaks completely.

However, [this comment](https://github.com/ValveSoftware/openvr/blob/master/headers/openvr.h#L1638-L1639) indicates that there may be a way to provide a separate default.vrsettings file that does not interfere with the one provided by Valve by creating your own driver_xxx directory. When this works then this would be the preferred way.

**Comment by LibreVR** [comment] 2016-12-14 18:42
> (2) you need to update Revive everytime Valve updates the default.vrsettings

I'm not so sure about that, `default.vrsettings` passes local data cache verification even if I edit it. So Valve may just parse that file and set all their defaults there, I mean they even recommend in the documentation that you add your settings there.

> (2) SteamVR could be completely broken when someone installs an outdated Revive version which misses some newly added default values

Revive would not replace `default.vrsettings`, it would parse it and add its own values.

> Revive could be completely broken whenever SteamVR updates the default.vrsettings and erases all Revive defaults.

Revive could still fallback to its internal default settings if the defaults are missing. The only thing that would break in this case is your options tab.

> However, this comment indicates that there may be a way to provide a separate default.vrsettings file that does not interfere with the one provided by Valve by creating your own driver_xxx directory.

That advice only goes for custom drivers, it's not intended for applications. According to that comment, applications should provide the defaults in the runtime directory.

**Comment by matzman666** [comment] 2016-12-14 19:33
> So Valve may just parse that file and set all their defaults there, I mean they even recommend in the documentation that you add your settings there.

Would make sense that they do it this way. If this is the case, then yeah option 2 is the way to go.

**Comment by LibreVR** [comment] 2016-12-16 16:22
Okay, I've implemented the runtime defaults for the next release: https://github.com/LibreVR/Revive/commit/fc16a42455c8b6e1678898bee90adc1262020af4

https://github.com/LibreVR/Revive/blob/master/Revive/Settings.h

**Comment by LibreVR** [comment] 2016-12-16 17:23
Also done: https://github.com/LibreVR/Revive/commit/e64e0c4279ba5302d7335361c7900717a6d7a4e6

**Comment by matzman666** [comment] 2016-12-16 21:15
Just in time. I am basically finished the revive settings tab, the only thing missing are determining the value ranges of the sliders and the precision of the values, and some more bug hunting.

Regarding the value ranges and precision, here are my assumptions and questions:

- `pixelsPerDisplayPixel` seems to be equivalent OpenVR's `RenderTargetMultiplier`; A precision of 0.1 should be sufficient.
- `ThumbDeadzone` seems to be [0, 1); 0.1 precise enough or better 0.01?
- `ThumbSensitivity ` seems to be (0, +inf), but what is a reasonable max value for the slider? 0.1 precise enough or better 0.01?
- `TouchPitch/Yaw/Poll` is [-180°, +180°]? Integer precision enough?
- `TouchX/Y/Z` is (-inf, +inf) with millimeter precision.
- Are there any defaults for `PlayerHeight `und `EyeHeight`?

**Comment by LibreVR** [comment] 2016-12-16 21:33
- It's equivalent, but it's important to note that it applies on top of the render target multiplier set in OpenVR
- I think it's better to have more precision for the deadzone, it's mainly for fine tuning, it's unlikely that you'd go much higher than the default.
- The sensitivity (previously known as range) is a multiplier for the amount of movement over the touchpad. The default of 2.0 means you'd have to move your thumb over half the touchpad to reach the other side of the thumbstick. I think 5.0 (one-fifth of the touchpad) is a good upper limit and 1.0 is the sane lower limit, any lower than 1.0 and you'd never reach the edge of the thumbstick.
- Yeah that's a good range, maybe a little better than integer though, I think I used 0.1 in my setup.
- Millimeter precision (0.001) is alright, it's unlikely that you'd move them more than a meter, but since it it not a slider it doesn't matter.

**Comment by matzman666** [comment] 2016-12-16 23:51
Commit 129c6e3db102707a8b6a4a79bb183ca5d78160da implements a first more or less complete version of the Revive tab. Attached you can find an already compiled archive for testing.

[v2.2pre1.zip](https://github.com/matzman666/OpenVR-AdvancedSettings/files/658500/v2.2pre1.zip)

**Comment by LibreVR** [comment] 2016-12-17 00:56
I'll try to make the options more interactive by allowing some settings like the touch angles and the toggle grip to be changed without restarting a game.

I wonder how efficient the OpenVR settings interface is though. I don't want to cause a bunch of File I/O every frame on the render thread.

**Comment by matzman666** [comment] 2016-12-17 01:33
I don't think there will be any file I/O. SteamVR most probably reads the settings file when it starts and then uses a cache to serve any request. To change settings at runtime you have to go through the API, just modifying the settings file accomplishes nothing.

Furthermore, you don't need to check every frame, I bet hardly anyone will notice anything when you only check every 30th frame. I check all settings every 1-2 seconds for changes, and there isn't any noticable strain on the system.

**Comment by LibreVR** [comment] 2016-12-17 01:51
I'm going to do some performance queries on those functions to see what kind of delay they introduce (if any). I can also just query these settings just after a frame submission where the CPU will be idle anyway.

**Comment by LibreVR** [comment] 2016-12-17 02:17
Okay, worst-case performance is 62 microseconds, average is 30 microseconds. As long as I don't query hundreds of settings I should be fine.

**Comment by CarrotSurvivor** [comment] 2016-12-20 16:40
yaaay collaboration at its finest :) looking forward !

**Comment by LibreVR** [comment] 2016-12-20 21:57
@matzman666 I'll try and provide feedback on your alpha version tomorrow once I have the new version of Revive ready.

**Comment by matzman666** [comment] 2016-12-21 00:30
Ok, here's a more up-to-date build:

[v2.2pre2.zip](https://github.com/matzman666/OpenVR-AdvancedSettings/files/665094/v2.2pre2.zip)

**Comment by matzman666** [comment] 2016-12-22 00:00
And another build. Reading the issue referenced above gave me the idea to let people create profiles of controller settings for easy switching between different set of settings.

[v2.2pre3.zip](https://github.com/matzman666/OpenVR-AdvancedSettings/files/667668/v2.2pre3.zip)

**Comment by LibreVR** [comment] 2016-12-22 00:07
You could switch those profiles based on the AppKey of the currently-running application, all Oculus games that have been detected by revive have an appkey like this: `revive.app.oculus-henry`

**Comment by matzman666** [comment] 2016-12-22 00:48
I don't think that supporting game-specific profiles directly in Revive makes much sense. Such things should be implemented in application launchers. It would make sense in your dashboard overlay though, but would require quite some effort to implement and would most probably not be realisable before 2017.

I think the best idea is to keep it as it is now, having to open a dashboard overlay to switch to another profile should be good enough for now.

**Comment by LibreVR** [comment] 2016-12-22 21:24
I've implemented automatic settings reloading for the controller settings: https://github.com/LibreVR/Revive/commit/c9a2bc69cb7b5143c898386d6a0b916b4713710d

I've tested it with your pre-release version, it's working great. Though we might want to change the precision after all, since players can enter values manually for more precision I think it'd make sense to make the spinner buttons a little more coarse.

**Comment by matzman666** [comment] 2016-12-23 21:08
It's a good idea to make the spinner buttons more coarse-grained. Will do that.

**Comment by Armada651** [comment] 2017-01-06 18:57
@matzman666 I released the new version of Revive which includes all the changes discussed here. It got some attention on /r/vive, so it would be nice if we could get a version out with the Revive tab. Are you ready for a release?

**Comment by matzman666** [comment] 2017-01-07 11:44
I am basically ready for release. The only thing I need to do is update the documentation and look into [this issue](https://github.com/ValveSoftware/openvr/issues/348) (Valve claims to have fixed it, but preliminary tests have shown that the behaviour of the message overlay has not changed at all. I now have to do some more extensive testing to see if the problem is on my side or some Valve engineer just forgot to push to master) and adjust accordingly.

**Comment by matzman666** [comment] 2017-01-07 15:39
I just released v2.2 with Revive support. Therefore I close this issue. I think the best is to open a new issue when problems arise.

**Closed by matzman666** 2017-01-07 15:39 UTC

**Comment by Armada651** [comment] 2017-01-07 17:51
Thanks for releasing it so quickly, I'll give you a heads up next time.

**Comment by matzman666** [comment] 2017-01-07 20:29
I was basically waiting with a 99% complete version, so it was not a big deal.
